name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'  # 使用 LTS 版本的 Node.js
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: Build
      run: npm run build
    - name: Run lint
      run: npm run lint
    - name: Preview deployment
      run: npm run preview
